# MyCra Death Message v1.2.0
# @author     ucchy
# @license    GPLv3
# @copyright  Copyright ucchy 2013

# Output to server.log
loggingDeathMessage: false

# Suppress death message exclude OPs.
suppressDeathMessage: false

# Append world name to prefix.
prefixWorld: true